####################################### Check Login 
GET http://localhost:5000/api/auth/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVmOWIyMDBjNDQzOGIzMDRmZTAwMjkiLCJpYXQiOjE2ODM5OTU4NTd9.VgCJb7ktNDDIC_83ndsaSlCpxIfYAEcJfo5TZfyrR1Q


############################################# REGISTER
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "Hanoi",
    "password": "01234"
}

############################################# LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "thuan",
    "password": "1234"
}

################################# CREATE SKILL
POST http://localhost:5000/api/skills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVmOWIyMDBjNDQzOGIzMDRmZTAwMjkiLCJpYXQiOjE2ODQ0Mjg4OTh9.nD-_3RcE-A5KqWNWFFYIVFLT9kOMtggeFrH8tBIA9tE

{
    "title" : "LEARN 3",
    "description": "Test Card",
    "url": "youtube.com",
    "status": "LEARNED"
}

################################# GET SKILL
GET http://localhost:5000/api/skills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVmOWIyMDBjNDQzOGIzMDRmZTAwMjkiLCJpYXQiOjE2ODM5OTU4NTd9.VgCJb7ktNDDIC_83ndsaSlCpxIfYAEcJfo5TZfyrR1Q

################################# UPDATE SKILL
PUT http://localhost:5000/api/skills/6466588cf116c6591df101d6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVmOWIyMDBjNDQzOGIzMDRmZTAwMjkiLCJpYXQiOjE2ODQ0Mjg4OTh9.nD-_3RcE-A5KqWNWFFYIVFLT9kOMtggeFrH8tBIA9tE

{
    "title": "LEARN 2",
    "description": "Test Card",
    "url": "https://youtube.com",
    "status": "LEARNING"
}


################################# UPDATE SKILL
DELETE http://localhost:5000/api/skills/645fbcdfae0cb5dac7669a03
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVmOWIyMDBjNDQzOGIzMDRmZTAwMjkiLCJpYXQiOjE2ODM5OTU4NTd9.VgCJb7ktNDDIC_83ndsaSlCpxIfYAEcJfo5TZfyrR1Q
